# Prediction Bias
Let's look at the prediction bias for Payer Model Test

## Imports

In [ ]:
from google.colab import auth
auth.authenticate_user()
print('Authenticated')

Authenticated

In [ ]:
import numpy as np
import sqlparse
import pandas as pd
from google.cloud import bigquery

%load_ext google.colab.data_table
import plotly.express as px

In [ ]:
# %%bigquery --project unity-ads-ds-prd
# SELECT * FROM unity-ai-data-prd.ads_events_raw.INFORMATION_SCHEMA.COLUMN_FIELD_PATHS
# where table_name='ads_events_operativeecpm_v1'

In [ ]:
# %%bigquery --project unity-ads-ds-prd
# SELECT * FROM unity-ads-bi-prd.rawevents.INFORMATION_SCHEMA.COLUMN_FIELD_PATHS
# where table_name='operativeecpm_installs_outcomes_contextual'

In [ ]:
# %%bigquery --project unity-ads-ds-prd
# SELECT * FROM unity-ai-data-prd.ads_events_raw.INFORMATION_SCHEMA.COLUMN_FIELD_PATHS
# where table_name='ads_events_operativeecpm_v0'

In [ ]:
# %%bigquery --project unity-ads-ds-prd
# SELECT * FROM unity-ads-bi-prd.rawevents.INFORMATION_SCHEMA.COLUMN_FIELD_PATHS
# where table_name='operativeecpm_installs_outcomes_contextual'

In [ ]:
# %%bigquery --project unity-ads-ds-prd
# SELECT * FROM unity-ai-data-prd.mz_dcpi_raw.INFORMATION_SCHEMA.COLUMN_FIELD_PATHS
# where table_name='mz_dcpi_valuation_v1'
# # operativeecpm_installs_outcomes_contextual

In [ ]:
# %%bigquery --project unity-ads-ds-prd
# SELECT * FROM unity-ai-data-prd.mz_dcpi_raw.INFORMATION_SCHEMA.COLUMN_FIELD_PATHS
# where table_name='mz_dcpi_valuation_v1'

#v11_payer - Bias exploration Query

In [ ]:
%%bigquery payer_df_all --project unity-ads-bi-prd
WITH PREDS as (
  SELECT
    submit_date,
    -- Updated version logic using CASE and LIKE
    CASE
      WHEN body.app_event_model_version LIKE '%v11-payer%' THEN 'v11-payer'
      WHEN body.app_event_model_version LIKE '%ctx1i-1a%' THEN 'ctx1i'
      WHEN body.app_event_model_version LIKE '%bhv1n-1a%' THEN 'bhv1n'
      ELSE null
    END as app_event_model_version,
    body.auction_id,
    body.app_event_p as pred,
    body.max_cst as target_cpe,
    body.cst as cost,
  FROM `unity-ai-data-prd.mz_dcpi_raw.mz_dcpi_prediction_v1`
  WHERE (submit_date >= "2026-03-29" and submit_date <= "2026-04-12")
  AND body.app_event_p > 0
  AND body.app_event_type = "purchase"
),

OUTCOMES AS (
  SELECT
    auctionId,
    campaignSpend,
    cum_deposit_capped_count_d0,
    cum_deposit_capped_count_d1,
    cum_deposit_capped_count_d2,
    cum_deposit_capped_count_d3,
    cum_deposit_capped_count_d4,
    cum_deposit_capped_count_d5,
    cum_deposit_capped_count_d6,
    cum_deposit_capped_count_d7,

    (CASE WHEN cum_deposit_capped_count_d0 > 0 THEN 1 ELSE 0 END) AS payer_label_d0,
    (CASE WHEN cum_deposit_capped_count_d1 > 0 THEN 1 ELSE 0 END) AS payer_label_d1,
    (CASE WHEN cum_deposit_capped_count_d2 > 0 THEN 1 ELSE 0 END) AS payer_label_d2,
    (CASE WHEN cum_deposit_capped_count_d3 > 0 THEN 1 ELSE 0 END) AS payer_label_d3,
    (CASE WHEN cum_deposit_capped_count_d4 > 0 THEN 1 ELSE 0 END) AS payer_label_d4,
    (CASE WHEN cum_deposit_capped_count_d5 > 0 THEN 1 ELSE 0 END) AS payer_label_d5,
    (CASE WHEN cum_deposit_capped_count_d6 > 0 THEN 1 ELSE 0 END) AS payer_label_d6,
    (CASE WHEN cum_deposit_capped_count_d7 > 0 THEN 1 ELSE 0 END) AS payer_label_d7,

    cum_deposit_capped_sum_d0,
    cum_deposit_capped_sum_d1,
    cum_deposit_capped_sum_d2,
    cum_deposit_capped_sum_d3,
    cum_deposit_capped_sum_d4,
    cum_deposit_capped_sum_d5,
    cum_deposit_capped_sum_d6,
    cum_deposit_capped_sum_d7,
    FROM `unity-data-ads-core-prd.ads_secondary_conversion.operativeecpm_installs_outcomes_contextual`
    WHERE (adRequestTimestamp >= TIMESTAMP("2026-03-29") and adRequestTimestamp <= TIMESTAMP("2026-04-12"))
)

SELECT
  submit_date,
  app_event_model_version,
  COUNT(*) as installs,
  SUM(pred) as sum_pred,
  AVG(pred) as avg_pred,

  SUM(target_cpe) as sum_tcpe,
  AVG(target_cpe) as avg_tcpe,
  SUM(cost) as sum_cost,
  AVG(cost) as avg_cost,

  SUM(campaignSpend) as sum_campaign_spend,

  SUM(payer_label_d0) as sum_payer_label_d0,
  SUM(payer_label_d1) as sum_payer_label_d1,
  SUM(payer_label_d2) as sum_payer_label_d2,
  SUM(payer_label_d3) as sum_payer_label_d3,
  SUM(payer_label_d4) as sum_payer_label_d4,
  SUM(payer_label_d5) as sum_payer_label_d5,
  SUM(payer_label_d6) as sum_payer_label_d6,
  SUM(payer_label_d7) as sum_payer_label_d7,

  SUM(cum_deposit_capped_count_d0) as sum_capped_count_d0,
  SUM(cum_deposit_capped_count_d1) as sum_capped_count_d1,
  SUM(cum_deposit_capped_count_d2) as sum_capped_count_d2,
  SUM(cum_deposit_capped_count_d3) as sum_capped_count_d3,
  SUM(cum_deposit_capped_count_d4) as sum_capped_count_d4,
  SUM(cum_deposit_capped_count_d5) as sum_capped_count_d5,
  SUM(cum_deposit_capped_count_d6) as sum_capped_count_d6,
  SUM(cum_deposit_capped_count_d7) as sum_capped_count_d7,

  SUM(cum_deposit_capped_sum_d0) as sum_capped_deposit_d0,
  SUM(cum_deposit_capped_sum_d1) as sum_capped_deposit_d1,
  SUM(cum_deposit_capped_sum_d2) as sum_capped_deposit_d2,
  SUM(cum_deposit_capped_sum_d3) as sum_capped_deposit_d3,
  SUM(cum_deposit_capped_sum_d4) as sum_capped_deposit_d4,
  SUM(cum_deposit_capped_sum_d5) as sum_capped_deposit_d5,
  SUM(cum_deposit_capped_sum_d6) as sum_capped_deposit_d6,
  SUM(cum_deposit_capped_sum_d7) as sum_capped_deposit_d7,
FROM PREDS
-- Changed to INNER JOIN or ensure PREDS is LEFT to keep the mapped versions consistent
RIGHT JOIN OUTCOMES ON OUTCOMES.auctionId = PREDS.auction_id
WHERE pred > 0
GROUP BY 1, 2
ORDER BY 1, 2

Query is running:   0%|          |

Downloading:   0%|          |

In [ ]:
payer_df_all

Warning: Total number of columns (34) exceeds max_columns (20). Falling back to pandas display.

,submit_date,app_event_model_version,installs,sum_pred,avg_pred,sum_tcpe,avg_tcpe,sum_cost,avg_cost,sum_campaign_spend,...,sum_capped_count_d6,sum_capped_count_d7,sum_capped_deposit_d0,sum_capped_deposit_d1,sum_capped_deposit_d2,sum_capped_deposit_d3,sum_capped_deposit_d4,sum_capped_deposit_d5,sum_capped_deposit_d6,sum_capped_deposit_d7
0,2026-03-29,bhv1n,869,40.027658,0.046062,53763940000,6.186875e+07,2258441514,2.598897e+06,2258441514,...,33,35,61.807570,1511.393094,2946.559830,2950.298391,5465.117863,7261.106486,7320.358486,7336.248486
1,2026-03-29,ctx1i,899,59.795531,0.066513,43412650000,4.828993e+07,2503638045,2.784914e+06,2503638045,...,48,52,89.729859,90.944859,90.944859,90.944859,90.944859,90.944859,403.744859,517.274859
2,2026-03-29,v11-payer,1275,89.721261,0.070370,72520750000,5.687902e+07,5176174576,4.059745e+06,5176174576,...,64,67,125.362501,136.101501,136.101501,136.101501,68.973891,71.457891,345.267891,371.952132
3,2026-03-30,bhv1n,967,44.974848,0.046510,65889550000,6.813811e+07,2843675566,2.940719e+06,2843675566,...,26,26,669.206176,3315.300737,3336.290737,3336.290737,3336.290737,3336.290737,4077.258541,4077.258541
4,2026-03-30,ctx1i,751,48.297409,0.064311,34872880000,4.643526e+07,1836228994,2.445045e+06,1836228994,...,24,24,44.000000,44.000000,44.000000,44.000000,44.000000,60.000000,106.530000,106.530000
5,2026-03-30,v11-payer,976,68.710391,0.070400,54316530000,5.565218e+07,3826569949,3.920666e+06,3826569949,...,53,56,60.443832,60.443832,60.443832,61.678832,76.419921,85.836921,269.326921,390.356921
6,2026-03-31,bhv1n,778,38.430931,0.049397,56160540000,7.218578e+07,2487350744,3.197109e+06,2487350744,...,31,31,92.379082,98.356082,128.326082,128.326082,128.326082,128.326082,141.316082,141.316082
7,2026-03-31,ctx1i,685,47.149240,0.068831,32594880000,4.758377e+07,1923600468,2.808176e+06,1923600468,...,21,22,98.000000,98.000000,98.000000,98.000000,98.000000,98.000000,223.320000,231.710000
8,2026-03-31,v11-payer,801,58.506729,0.073042,44542960000,5.560919e+07,3283926288,4.099783e+06,3283926288,...,36,37,116.025919,142.228961,164.640961,189.562271,189.562271,189.562271,547.252271,560.242271
9,2026-04-01,bhv1n,624,32.100694,0.051443,43622220000,6.990740e+07,2128614146,3.411241e+06,2128614146,...,40,40,607.773487,615.233487,615.233487,615.233487,598.478542,599.725305,612.715305,612.715305
10,2026-04-01,ctx1i,381,29.855262,0.078360,21940990000,5.758790e+07,1118122815,2.934706e+06,1118122815,...,16,16,147.150003,147.150003,165.150003,176.150003,176.150003,176.150003,205.230003,205.230003
11,2026-04-01,v11-payer,462,39.105158,0.084643,27313390000,5.911989e+07,1955187793,4.232008e+06,1955187793,...,26,27,148.315480,158.815480,166.815480,166.815480,168.028051,168.028051,281.588051,294.578051
12,2026-04-02,bhv1n,610,29.556697,0.048454,44019330000,7.216284e+07,2111951520,3.462216e+06,2111951520,...,104,110,1473.743823,2972.709823,3049.505075,3255.704075,3258.174075,3498.857075,3714.941075,3876.931075
13,2026-04-02,ctx1i,167,13.884947,0.083143,12810770000,7.671120e+07,648639524,3.884069e+06,648639524,...,11,11,112.457092,125.457092,135.457092,135.457092,135.457092,135.457092,135.457092,135.457092
14,2026-04-02,v11-payer,516,34.669330,0.067189,24019360000,4.654915e+07,1659042810,3.215199e+06,1659042810,...,14,15,27.539695,41.233179,41.233179,54.452920,56.926920,56.926920,56.926920,64.475514
15,2026-04-03,bhv1n,733,37.746488,0.051496,51237660000,6.990131e+07,2430374078,3.315654e+06,2430374078,...,31,31,112.226092,113.463092,115.453092,117.973092,117.973092,124.236092,126.748092,126.748092
16,2026-04-03,ctx1i,158,15.777606,0.099858,9860330000,6.240715e+07,578530633,3.661586e+06,578530633,...,5,5,31.679136,31.679136,31.679136,42.679136,42.679136,42.679136,42.679136,42.679136
17,2026-04-03,v11-payer,342,30.278158,0.088533,27655670000,8.086453e+07,2178586360,6.370136e+06,2178586360,...,18,18,75.734518,76.979449,76.979449,107.641911,79.424130,79.424130,88.435684,88.435684
18,2026-04-04,bhv1n,661,30.098916,0.045535,46810330000,7.081744e+07,2223883833,3.364423e+06,2223883833,...,20,20,24.867750,26.109750,26.109750,38.840388,47.485388,48.760388,48.760388,48.760388
19,2026-04-04,ctx1i,123,11.316394,0.092003,8455540000,6.874423e+07,555837555,4.519005e+06,555837555,...,10,10,1349.055784,1349.055784,1349.055784,1349.055784,5368.322556,5368.322556,6713.822799,6713.822799
20,2026-04-04,v11-payer,317,25.656932,0.080937,28401120000,8.959344e+07,2430643600,7.667645e+06,2430643600,...,31,32,92.966223,106.668923,133.169772,165.031281,127.234245,152.786571,259.042013,259.560789
21,2026-04-05,bhv1n,931,42.050880,0.045167,64645330000,6.943644e+07,2845404858,3.056289e+06,2845404858,...,16,18,98.365747,108.358747,121.110161,123.704042,108.524161,111.054161,111.054161,113.622161
22,2026-04-05,ctx1i,97,9.389706,0.096801,6018110000,6.204237e+07,355852971,3.668587e+06,351286534,...,8,8,69.000000,69.000000,69.000000,69.000000,69.000000,74.024000,75.308000,75.308000
23,2026-04-05,v11-payer,335,26.147329,0.078052,30894780000,9.222322e+07,2330451593,6.956572e+06,2330451593,...,48,48,156.131313,368.942126,395.597651,399.417020,404.921018,404.921018,404.921018,404.921018
24,2026-04-06,bhv1n,736,33.977247,0.046165,59259880000,8.051614e+07,2762121505,3.752882e+06,2762121505,...,22,22,113.638660,126.389866,128.913866,128.913866,128.913866,131.481866,131.481866,131.481866
25,2026-04-06,ctx1i,158,17.035507,0.107820,13103100000,8.293101e+07,890884258,5.638508e+06,890884258,...,9,10,60.247594,60.247594,71.247594,71.247594,71.247594,71.247594,86.335594,88.895594
26,2026-04-06,v11-payer,241,19.235694,0.079816,25964210000,1.077353e+08,2048832822,8.501381e+06,2048832822,...,14,16,2651.663706,2654.200684,2662.190684,2662.190684,2689.091676,2702.546679,2702.546679,2717.364667
27,2026-04-07,bhv1n,560,25.974312,0.046383,43485320000,7.765236e+07,2005670300,3.581554e+06,2005670300,...,13,13,90.485389,105.735915,108.247915,108.247915,90.333520,92.920098,92.920098,92.920098
28,2026-04-07,ctx1i,168,17.326205,0.103132,15356990000,9.141065e+07,900632856,5.360910e+06,900632856,...,8,8,77.630159,77.630159,90.630159,90.630159,90.630159,90.630159,90.630159,90.630159
29,2026-04-07,v11-payer,280,20.985509,0.074948,29898580000,1.067806e+08,2095570095,7.484179e+06,2095570095,...,19,19,4076.596370,4080.415445,4080.415445,4080.415445,4059.918344,4059.918344,4059.918344,4059.918344
30,2026-04-08,bhv1n,690,30.112956,0.043642,49323100000,7.148275e+07,2152101815,3.118988e+06,2144238037,...,<NA>,<NA>,78.962763,132.419108,133.694108,134.978108,NaN,NaN,NaN,NaN
31,2026-04-08,ctx1i,181,12.405095,0.068536,20700660000,1.143683e+08,1033033024,5.707365e+06,1033033024,...,<NA>,<NA>,82.758297,98.019897,98.019897,98.019897,NaN,NaN,NaN,NaN
32,2026-04-08,v11-payer,221,14.386322,0.065096,21394200000,9.680633e+07,1448547027,6.554511e+06,1448547027,...,<NA>,<NA>,105.248470,105.248470,105.248470,105.248470,NaN,NaN,NaN,NaN
33,2026-04-09,bhv1n,1085,42.050948,0.038757,65169770000,6.006430e+07,2688388852,2.477778e+06,2688388852,...,<NA>,<NA>,64.028639,66.587639,66.587639,77.587639,NaN,NaN,NaN,NaN
34,2026-04-09,ctx1i,217,19.113353,0.088080,17465320000,8.048535e+07,1006439350,4.637969e+06,1006439350,...,<NA>,<NA>,100.162734,125.269185,125.269185,125.269185,NaN,NaN,NaN,NaN
35,2026-04-09,v11-payer,407,16.588085,0.040757,29118910000,7.154523e+07,1469841152,3.611403e+06,1469841152,...,<NA>,<NA>,119.852749,119.852749,119.852749,119.852749,NaN,NaN,NaN,NaN
36,2026-04-10,bhv1n,1006,39.474598,0.039239,56129000000,5.579423e+07,2224823966,2.211555e+06,2224823966,...,<NA>,<NA>,109.731924,173.005924,174.289924,174.289924,NaN,NaN,NaN,NaN
37,2026-04-10,ctx1i,216,19.484696,0.090207,15154000000,7.015741e+07,823627756,3.813091e+06,823627756,...,<NA>,<NA>,48.000000,48.423859,48.423859,48.423859,NaN,NaN,NaN,NaN
38,2026-04-10,v11-payer,377,17.263524,0.045792,27897720000,7.399926e+07,1530796433,4.060468e+06,1530796433,...,<NA>,<NA>,4120.080399,4120.080399,4121.393177,4122.783177,NaN,NaN,NaN,NaN
39,2026-04-11,bhv1n,900,33.919045,0.037688,49640000000,5.515556e+07,1854449577,2.060500e+06,1854449577,...,<NA>,<NA>,65.387402,70.081402,70.081402,70.081402,NaN,NaN,NaN,NaN
40,2026-04-11,ctx1i,256,23.089952,0.090195,18215000000,7.115234e+07,959562540,3.748291e+06,959562540,...,<NA>,<NA>,95.500000,95.500000,95.500000,95.500000,NaN,NaN,NaN,NaN
41,2026-04-11,v11-payer,415,13.463586,0.032442,25030840000,6.031528e+07,1191257420,2.870500e+06,1191257420,...,<NA>,<NA>,91.354364,106.534364,62.268000,62.268000,NaN,NaN,NaN,NaN
42,2026-04-12,bhv1n,1,0.023006,0.023006,35000000,3.500000e+07,805214,8.052140e+05,805214,...,<NA>,<NA>,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
43,2026-04-12,v11-payer,1,0.038907,0.038907,35000000,3.500000e+07,1361730,1.361730e+06,1361730,...,<NA>,<NA>,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
payer_df_all.keys()

Index(['submit_date', 'app_event_model_version', 'installs', 'sum_pred',
       'avg_pred', 'sum_tcpe', 'avg_tcpe', 'sum_cost', 'avg_cost',
       'sum_campaign_spend', 'sum_payer_label_d0', 'sum_payer_label_d1',
       'sum_payer_label_d2', 'sum_payer_label_d3', 'sum_payer_label_d4',
       'sum_payer_label_d5', 'sum_payer_label_d6', 'sum_payer_label_d7',
       'sum_capped_count_d0', 'sum_capped_count_d1', 'sum_capped_count_d2',
       'sum_capped_count_d3', 'sum_capped_count_d4', 'sum_capped_count_d5',
       'sum_capped_count_d6', 'sum_capped_count_d7', 'sum_capped_deposit_d0',
       'sum_capped_deposit_d1', 'sum_capped_deposit_d2',
       'sum_capped_deposit_d3', 'sum_capped_deposit_d4',
       'sum_capped_deposit_d5', 'sum_capped_deposit_d6',
       'sum_capped_deposit_d7'],
      dtype='object')

In [ ]:
payer_df_all[["app_event_model_version", "sum_pred", 'sum_payer_label_d0', 'sum_capped_count_d0', 'sum_payer_label_d1', 'sum_capped_count_d1', 'sum_payer_label_d2', 'sum_capped_count_d2',
       'sum_payer_label_d3', 'sum_capped_count_d3', 'sum_payer_label_d4', 'sum_capped_count_d4', 'sum_payer_label_d5', 'sum_capped_count_d5',
       'sum_payer_label_d6', 'sum_capped_count_d6', 'sum_payer_label_d7', 'sum_capped_count_d7']]

,app_event_model_version,sum_pred,sum_payer_label_d0,sum_capped_count_d0,sum_payer_label_d1,sum_capped_count_d1,sum_payer_label_d2,sum_capped_count_d2,sum_payer_label_d3,sum_capped_count_d3,sum_payer_label_d4,sum_capped_count_d4,sum_payer_label_d5,sum_capped_count_d5,sum_payer_label_d6,sum_capped_count_d6,sum_payer_label_d7,sum_capped_count_d7
0,bhv1n,40.027658,18,21,22,25,23,27,24,28,24,30,24,31,25,33,25,35
1,ctx1i,59.795531,33,35,37,39,37,39,37,39,37,39,37,39,38,48,38,52
2,v11-payer,89.721261,44,48,49,54,49,54,49,54,48,53,49,55,50,64,52,67
3,bhv1n,44.974848,12,12,15,20,17,22,17,22,17,22,17,22,17,26,17,26
4,ctx1i,48.297409,15,16,16,17,17,18,18,19,18,19,19,20,20,24,20,24
5,v11-payer,68.710391,34,35,35,36,36,37,37,38,39,40,40,44,41,53,43,56
6,bhv1n,38.430931,20,26,20,27,21,30,21,30,21,30,21,30,21,31,21,31
7,ctx1i,47.149240,15,16,15,16,15,16,15,16,15,16,15,16,17,21,17,22
8,v11-payer,58.506729,17,18,19,20,21,25,23,27,23,27,23,27,31,36,32,37
9,bhv1n,32.100694,12,24,13,30,13,30,13,30,13,30,14,32,15,40,15,40
10,ctx1i,29.855262,7,10,7,10,8,11,8,12,8,12,9,13,11,16,11,16
11,v11-payer,39.105158,11,17,12,20,12,21,12,21,12,22,12,22,16,26,17,27
12,bhv1n,29.556697,7,8,10,77,12,82,12,86,13,88,13,95,13,104,13,110
13,ctx1i,13.884947,7,9,7,10,7,11,7,11,7,11,7,11,7,11,7,11
14,v11-payer,34.669330,6,6,8,8,8,8,10,12,11,14,11,14,11,14,12,15
15,bhv1n,37.746488,13,19,14,20,14,21,15,23,15,23,19,30,19,31,19,31
16,ctx1i,15.777606,3,4,3,4,3,4,4,5,4,5,4,5,4,5,4,5
17,v11-payer,30.278158,11,14,12,15,12,15,14,21,14,15,14,15,16,18,16,18
18,bhv1n,30.098916,7,8,8,9,8,11,9,14,10,17,11,19,11,20,11,20
19,ctx1i,11.316394,4,6,4,6,4,6,4,6,4,9,4,9,4,10,4,10
20,v11-payer,25.656932,7,7,9,9,11,14,12,23,11,23,11,25,11,31,11,32
21,bhv1n,42.050880,14,16,15,19,16,20,17,21,14,15,14,16,14,16,15,18
22,ctx1i,9.389706,4,5,4,5,4,5,4,5,4,5,5,7,5,8,5,8
23,v11-payer,26.147329,6,20,6,31,8,42,10,44,12,48,12,48,12,48,12,48
24,bhv1n,33.977247,13,17,14,18,15,20,15,20,15,20,16,22,16,22,16,22
25,ctx1i,17.035507,4,5,4,5,5,6,5,6,5,6,5,6,6,9,6,10
26,v11-payer,19.235694,4,7,5,9,7,11,7,11,8,13,8,14,8,14,9,16
27,bhv1n,25.974312,9,12,11,15,11,16,11,16,9,12,10,13,10,13,10,13
28,ctx1i,17.326205,6,7,6,7,6,8,6,8,6,8,6,8,6,8,6,8
29,v11-payer,20.985509,16,22,16,23,16,23,16,23,13,19,13,19,13,19,13,19
30,bhv1n,30.112956,13,18,16,21,16,22,17,23,0,<NA>,0,<NA>,0,<NA>,0,<NA>
31,ctx1i,12.405095,7,7,8,8,8,8,8,8,0,<NA>,0,<NA>,0,<NA>,0,<NA>
32,v11-payer,14.386322,13,15,13,15,13,15,13,15,0,<NA>,0,<NA>,0,<NA>,0,<NA>
33,bhv1n,42.050948,13,15,15,17,15,17,16,18,0,<NA>,0,<NA>,0,<NA>,0,<NA>
34,ctx1i,19.113353,6,7,7,8,7,8,7,8,0,<NA>,0,<NA>,0,<NA>,0,<NA>
35,v11-payer,16.588085,8,24,8,24,8,24,8,24,0,<NA>,0,<NA>,0,<NA>,0,<NA>
36,bhv1n,39.474598,12,15,13,28,14,29,14,29,0,<NA>,0,<NA>,0,<NA>,0,<NA>
37,ctx1i,19.484696,3,3,4,4,4,4,4,4,0,<NA>,0,<NA>,0,<NA>,0,<NA>
38,v11-payer,17.263524,14,23,14,23,15,24,15,25,0,<NA>,0,<NA>,0,<NA>,0,<NA>
39,bhv1n,33.919045,9,13,11,17,11,17,11,17,0,<NA>,0,<NA>,0,<NA>,0,<NA>
40,ctx1i,23.089952,6,6,6,6,6,6,6,6,0,<NA>,0,<NA>,0,<NA>,0,<NA>
41,v11-payer,13.463586,9,17,9,19,7,15,7,15,0,<NA>,0,<NA>,0,<NA>,0,<NA>
42,bhv1n,0.023006,0,<NA>,0,<NA>,0,<NA>,0,<NA>,0,<NA>,0,<NA>,0,<NA>,0,<NA>
43,v11-payer,0.038907,0,<NA>,0,<NA>,0,<NA>,0,<NA>,0,<NA>,0,<NA>,0,<NA>,0,<NA>

In [ ]:
def draw_bias_comparison(dataframe: pd.DataFrame, outcome_column: str, prediction_column: str, title:str):
    new_list = []

    for payer_version in dataframe['app_event_model_version'].unique():
        temp_df = dataframe[dataframe['app_event_model_version'] == payer_version]
        for day in range(0, 8):
            current_outcome_col = outcome_column + str(day)
            # Get indices where the current outcome column is not 0 (and not NaN implicitly by pandas sum)
            # Also ensure that it's not NaN for robustness
            valid_indices = temp_df[(temp_df[current_outcome_col].notna()) & (temp_df[current_outcome_col] != 0)].index

            # Sum prediction_column and outcome_column only for valid_indices
            sum_prediction_for_day = temp_df.loc[valid_indices, prediction_column].sum()
            sum_outcome_for_day = temp_df.loc[valid_indices, current_outcome_col].sum()

            # print(day, sum_prediction_for_day, sum_outcome_for_day)

            if sum_outcome_for_day != 0: # This check is still good practice to catch any edge cases
                bias_value = ((sum_prediction_for_day / sum_outcome_for_day) - 1)
            else:
                bias_value = None # Or np.nan, depending on how you want to represent it

            new_list.append([f"d{day}", bias_value, payer_version])


    new_df = pd.DataFrame(new_list, columns=["dayX", "bias", "payer_version"])
    # print(new_df)

    fig = px.line(new_df, x='dayX', y='bias', color="payer_version", title=title, text=new_df['bias'].round(2))
    fig.update_traces(textposition='top center') # Position the text at the top center of each point
    display(fig)

In [ ]:
#v11_payer - Bias exploration Query

## Model Bias by dx

In [ ]:
draw_bias_comparison(
    payer_df_all,
    outcome_column="sum_payer_label_d",
    prediction_column="sum_pred",
    title="Payer Model Bias VS DayX - (Prediction (Payer rate) / Outcome(sum_payer_label_dx) - 1) "
)

## Product Bias by Dx

In [ ]:
def draw_product_bias_comparison_dx(dataframe: pd.DataFrame, title: str):
    new_list = []

    for payer_version in dataframe['app_event_model_version'].unique():
        temp_df = dataframe[dataframe['app_event_model_version'] == payer_version].copy()

        for day in range(0, 8):
            capped_count_col = f'sum_capped_count_d{day}'

            # Filter for rows where we have valid data for this specific day
            valid_data = temp_df[(temp_df[capped_count_col].notna()) & (temp_df[capped_count_col] != 0)]

            if not valid_data.empty:
                # Aggregated calculation: (Sum of Costs / Sum of Counts) / Avg Target CPE - 1
                # This matches the logic of 'Overall Product Bias'
                total_cost = valid_data['sum_cost'].sum()
                total_count = valid_data[capped_count_col].sum()
                avg_target_cpe = valid_data['avg_tcpe'].mean()

                observed_cpe = total_cost / total_count
                bias_value = (observed_cpe / avg_target_cpe) - 1
            else:
                bias_value = None

            new_list.append([f"d{day}", bias_value, payer_version])

    new_df = pd.DataFrame(new_list, columns=["dayX", "bias", "payer_version"])

    fig = px.line(new_df, x='dayX', y='bias', color="payer_version",
                  title=title, text=new_df['bias'].round(2))
    fig.add_hline(y=0, line_dash="dash", line_color="black")
    fig.update_traces(textposition='top center')
    display(fig)

draw_product_bias_comparison_dx(
    payer_df_all,
    title="Product Bias VS DayX - ((Observed CPE / Target CPE) - 1)"
)

# Prediction: Model payer rate prediction per day per model

In [ ]:
model_performance = payer_df_all.groupby('app_event_model_version').agg(
    avg_prediction=('avg_pred', 'mean'),
    avg_cpi=('avg_cost', 'mean'),
    avg_spend=('sum_cost', 'mean'),
    avg_tcpe=('avg_tcpe', 'mean'),
    avg_installs=('installs', 'mean')
).reset_index()

display(model_performance)

,app_event_model_version,avg_prediction,avg_cpi,avg_spend,avg_tcpe,avg_installs
0,bhv1n,0.043930,2.890335e+06,2201203832.533333,6.600556e+07,743.4
1,ctx1i,0.085557,3.972302e+06,1081045056.357143,7.002192e+07,318.357143
2,v11-payer,0.066062,4.997728e+06,2175119309.866667,7.257818e+07,464.4

## Average Prediction

In [ ]:
fig = px.line(
    payer_df_all,
    x='submit_date',
    y=f'avg_pred',
    color='app_event_model_version',
    title=f'Average Payer prediction VS Submit Date',
    labels={
        'submit_date': 'Submit Date',
        'app_event_model_version': 'App Event Model Version'
    },
    text=payer_df_all[f'avg_pred'].round(5) # Add absolute numbers as text, rounded to 2 decimal places
)
fig.update_traces(textposition='top center') # Position the text at the top center of each point
fig.show()

## Average target CPE

In [ ]:
fig = px.line(
    payer_df_all,
    x='submit_date',
    y=f'avg_tcpe',
    color='app_event_model_version',
    title=f'Average taget CPE VS Submit Date',
    labels={
        'submit_date': 'Submit Date',
        'app_event_model_version': 'App Event Model Version'
    },
    text=(payer_df_all[f'avg_tcpe'] / 1000000).round(2) # Add absolute numbers as text, rounded to 2 decimal places
)
fig.update_traces(textposition='top center') # Position the text at the top center of each point
fig.show()

## Average Spend

In [ ]:
print()
fig = px.line(
    payer_df_all,
    x='submit_date',
    y=f'avg_cost',
    color='app_event_model_version',
    title=f'Average Spend VS Submit Date',
    labels={
        'submit_date': 'Submit Date',
        'app_event_model_version': 'App Event Model Version'
    },
    text=(payer_df_all[f'avg_cost'] / 1000000).round(5) # Add absolute numbers as text, rounded to 2 decimal places
)
fig.update_traces(textposition='top center') # Position the text at the top center of each point
fig.show()

## Average Installs

In [ ]:
fig = px.line(
    payer_df_all,
    x='submit_date',
    y=f'installs',
    color='app_event_model_version',
    title=f'Average Installs VS Submit Date',
    labels={
        'submit_date': 'Submit Date',
        'app_event_model_version': 'App Event Model Version'
    },
    text=(payer_df_all[f'installs']).round(0) # Add absolute numbers as text, rounded to 2 decimal places
)
fig.update_traces(textposition='top center') # Position the text at the top center of each point
fig.show()

## Payer Rate

sum_payer_label_dx / installs

In [ ]:
def payer_rate_plot(payer_df_all):
  for i in range(0, 8):
    payer_df_all[f'payer_date_d{i}'] = ( payer_df_all[f'sum_payer_label_d{i}'] / payer_df_all[f'installs']) * 100

    # Calculate overall payer rate for each model for the current day i
    valid_data_df = payer_df_all[
        (payer_df_all[f'sum_payer_label_d{i}'].notna()) &
        (payer_df_all[f'sum_payer_label_d{i}'] != 0)
    ]
    overall_payer_rates = valid_data_df.groupby('app_event_model_version').agg(
        total_sum_payer_label = (f'sum_payer_label_d{i}', 'sum'),
        total_installs = ('installs', 'sum')
    ).reset_index()
    overall_payer_rates[f'overall_payer_rate_d{i}'] = (overall_payer_rates['total_sum_payer_label'] / overall_payer_rates['total_installs']) * 100

    # Create a subtitle string for the overall rates
    subtitle_parts = []
    for index, row in overall_payer_rates.iterrows():
        subtitle_parts.append(f'{row["app_event_model_version"]}: {row[f"overall_payer_rate_d{i}"]:.2f}%')
    subtitle_text = 'Average Rates: ' + '  |  '.join(subtitle_parts)

    fig = px.line(
        payer_df_all,
        x='submit_date',
        y=f'payer_date_d{i}',
        color='app_event_model_version',
        title=f'Payer Rate D{i} (sum_payer_label_d{i} / installs) * 100 VS Submit Date', # Assign only the main title here
        text=payer_df_all[f'payer_date_d{i}'].round(2) # Add bias numbers as text, rounded to 2 decimal places
    )

    # Add the subtitle as an annotation
    fig.update_layout(
        annotations=[
            dict(
                text=subtitle_text,
                xref='paper',
                yref='paper',
                x=0.5,
                y=0.96, # Adjust y to position it below the main title. This usually works well.
                showarrow=False,
                font=dict(size=15), # Smaller font size
                xanchor='center',
                yanchor='top' # Anchor the top of the text to the y position
            )
        ]
    )

    fig.add_hline(y=0)
    fig.update_traces(textposition='top center') # Position the text at the top center of each point
    fig.show()

payer_rate_plot(payer_df_all)

## Purchase Rate

sum_purchase_label_dx / installs

In [ ]:
def purchase_rate_plot(payer_df_all):
  for i in range(0, 8):
    payer_df_all[f'purchase_date_d{i}'] = ( payer_df_all[f'sum_capped_count_d{i}'] / payer_df_all[f'installs']) * 100

    # Calculate overall purchase rate for each model for the current day i
    valid_data_df = payer_df_all[
        (payer_df_all[f'sum_capped_count_d{i}'].notna()) &
        (payer_df_all[f'sum_capped_count_d{i}'] != 0)
    ]
    overall_purchase_rates = valid_data_df.groupby('app_event_model_version').agg(
        total_sum_purchase_label = (f'sum_capped_count_d{i}', 'sum'),
        total_installs = ('installs', 'sum')
    ).reset_index()
    overall_purchase_rates[f'overall_purchase_rate_d{i}'] = (overall_purchase_rates[f'total_sum_purchase_label'] / overall_purchase_rates['total_installs']) * 100

    # Create a subtitle string for the overall rates
    subtitle_parts = []
    for index, row in overall_purchase_rates.iterrows():
        subtitle_parts.append(f'{row["app_event_model_version"]}: {row[f"overall_purchase_rate_d{i}"]:.2f}%')
    subtitle_text = 'Average Rates: ' + '  |  '.join(subtitle_parts)

    fig = px.line(
        payer_df_all,
        x='submit_date',
        y=f'purchase_date_d{i}',
        color='app_event_model_version',
        title=f'Purchase Rate D{i} (sum_capped_count_d{i} / installs) * 100 VS Submit Date',
        text=payer_df_all[f'purchase_date_d{i}'].round(2) # Add bias numbers as text, rounded to 2 decimal places
    )

    # Add the subtitle as an annotation
    fig.update_layout(
        annotations=[
            dict(
                text=subtitle_text,
                xref='paper',
                yref='paper',
                x=0.5,
                y=0.96, # Adjust y to position it below the main title. This usually works well.
                showarrow=False,
                font=dict(size=15), # Smaller font size
                xanchor='center',
                yanchor='top' # Anchor the top of the text to the y position
            )
        ]
    )

    fig.add_hline(y=0)
    fig.update_traces(textposition='top center') # Position the text at the top center of each point
    fig.show()

purchase_rate_plot(payer_df_all)

In [ ]:
payer_df_all[["submit_date","app_event_model_version", "installs", "sum_capped_count_d7"]]

   submit_date app_event_model_version  installs  sum_capped_count_d7
0   2026-03-29                   bhv1n       869                   35
1   2026-03-29                   ctx1i       899                   52
2   2026-03-29               v11-payer      1275                   67
3   2026-03-30                   bhv1n       967                   26
4   2026-03-30                   ctx1i       751                   24
5   2026-03-30               v11-payer       976                   56
6   2026-03-31                   bhv1n       778                   31
7   2026-03-31                   ctx1i       685                   22
8   2026-03-31               v11-payer       801                   37
9   2026-04-01                   bhv1n       624                   40
10  2026-04-01                   ctx1i       381                   16
11  2026-04-01               v11-payer       462                   27
12  2026-04-02                   bhv1n       610                  110
13  2026-04-02                   ctx1i       167                   11
14  2026-04-02               v11-payer       516                   15
15  2026-04-03                   bhv1n       733                   31
16  2026-04-03                   ctx1i       158                    5
17  2026-04-03               v11-payer       342                   18
18  2026-04-04                   bhv1n       661                   20
19  2026-04-04                   ctx1i       123                   10
20  2026-04-04               v11-payer       317                   32
21  2026-04-05                   bhv1n       931                   18
22  2026-04-05                   ctx1i        97                    8
23  2026-04-05               v11-payer       335                   48
24  2026-04-06                   bhv1n       736                   22
25  2026-04-06                   ctx1i       158                   10
26  2026-04-06               v11-payer       241                   16
27  2026-04-07                   bhv1n       560                   13
28  2026-04-07                   ctx1i       168                    8
29  2026-04-07               v11-payer       280                   19
30  2026-04-08                   bhv1n       690                 <NA>
31  2026-04-08                   ctx1i       181                 <NA>
32  2026-04-08               v11-payer       221                 <NA>
33  2026-04-09                   bhv1n      1085                 <NA>
34  2026-04-09                   ctx1i       217                 <NA>
35  2026-04-09               v11-payer       407                 <NA>
36  2026-04-10                   bhv1n      1006                 <NA>
37  2026-04-10                   ctx1i       216                 <NA>
38  2026-04-10               v11-payer       377                 <NA>
39  2026-04-11                   bhv1n       900                 <NA>
40  2026-04-11                   ctx1i       256                 <NA>
41  2026-04-11               v11-payer       415                 <NA>
42  2026-04-12                   bhv1n         1                 <NA>
43  2026-04-12               v11-payer         1                 <NA>

In [ ]:
payer_df_all

Warning: Total number of columns (50) exceeds max_columns (20). Falling back to pandas display.

,submit_date,app_event_model_version,installs,sum_pred,avg_pred,sum_tcpe,avg_tcpe,sum_cost,avg_cost,sum_campaign_spend,...,payer_date_d6,payer_date_d7,purchase_date_d0,purchase_date_d1,purchase_date_d2,purchase_date_d3,purchase_date_d4,purchase_date_d5,purchase_date_d6,purchase_date_d7
0,2026-03-29,bhv1n,869,40.027658,0.046062,53763940000,6.186875e+07,2258441514,2.598897e+06,2258441514,...,2.87687,2.87687,2.416571,2.87687,3.10702,3.222094,3.452244,3.567319,3.797468,4.027618
1,2026-03-29,ctx1i,899,59.795531,0.066513,43412650000,4.828993e+07,2503638045,2.784914e+06,2503638045,...,4.226919,4.226919,3.893215,4.338154,4.338154,4.338154,4.338154,4.338154,5.339266,5.784205
2,2026-03-29,v11-payer,1275,89.721261,0.070370,72520750000,5.687902e+07,5176174576,4.059745e+06,5176174576,...,3.921569,4.078431,3.764706,4.235294,4.235294,4.235294,4.156863,4.313725,5.019608,5.254902
3,2026-03-30,bhv1n,967,44.974848,0.046510,65889550000,6.813811e+07,2843675566,2.940719e+06,2843675566,...,1.758014,1.758014,1.240951,2.068252,2.275078,2.275078,2.275078,2.275078,2.688728,2.688728
4,2026-03-30,ctx1i,751,48.297409,0.064311,34872880000,4.643526e+07,1836228994,2.445045e+06,1836228994,...,2.663116,2.663116,2.130493,2.263648,2.396804,2.52996,2.52996,2.663116,3.195739,3.195739
5,2026-03-30,v11-payer,976,68.710391,0.070400,54316530000,5.565218e+07,3826569949,3.920666e+06,3826569949,...,4.20082,4.405738,3.586066,3.688525,3.790984,3.893443,4.098361,4.508197,5.430328,5.737705
6,2026-03-31,bhv1n,778,38.430931,0.049397,56160540000,7.218578e+07,2487350744,3.197109e+06,2487350744,...,2.699229,2.699229,3.341902,3.470437,3.856041,3.856041,3.856041,3.856041,3.984576,3.984576
7,2026-03-31,ctx1i,685,47.149240,0.068831,32594880000,4.758377e+07,1923600468,2.808176e+06,1923600468,...,2.481752,2.481752,2.335766,2.335766,2.335766,2.335766,2.335766,2.335766,3.065693,3.211679
8,2026-03-31,v11-payer,801,58.506729,0.073042,44542960000,5.560919e+07,3283926288,4.099783e+06,3283926288,...,3.870162,3.995006,2.247191,2.496879,3.121099,3.370787,3.370787,3.370787,4.494382,4.619226
9,2026-04-01,bhv1n,624,32.100694,0.051443,43622220000,6.990740e+07,2128614146,3.411241e+06,2128614146,...,2.403846,2.403846,3.846154,4.807692,4.807692,4.807692,4.807692,5.128205,6.410256,6.410256
10,2026-04-01,ctx1i,381,29.855262,0.078360,21940990000,5.758790e+07,1118122815,2.934706e+06,1118122815,...,2.887139,2.887139,2.624672,2.624672,2.887139,3.149606,3.149606,3.412073,4.199475,4.199475
11,2026-04-01,v11-payer,462,39.105158,0.084643,27313390000,5.911989e+07,1955187793,4.232008e+06,1955187793,...,3.463203,3.679654,3.679654,4.329004,4.545455,4.545455,4.761905,4.761905,5.627706,5.844156
12,2026-04-02,bhv1n,610,29.556697,0.048454,44019330000,7.216284e+07,2111951520,3.462216e+06,2111951520,...,2.131148,2.131148,1.311475,12.622951,13.442623,14.098361,14.42623,15.57377,17.04918,18.032787
13,2026-04-02,ctx1i,167,13.884947,0.083143,12810770000,7.671120e+07,648639524,3.884069e+06,648639524,...,4.191617,4.191617,5.389222,5.988024,6.586826,6.586826,6.586826,6.586826,6.586826,6.586826
14,2026-04-02,v11-payer,516,34.669330,0.067189,24019360000,4.654915e+07,1659042810,3.215199e+06,1659042810,...,2.131783,2.325581,1.162791,1.550388,1.550388,2.325581,2.713178,2.713178,2.713178,2.906977
15,2026-04-03,bhv1n,733,37.746488,0.051496,51237660000,6.990131e+07,2430374078,3.315654e+06,2430374078,...,2.592087,2.592087,2.592087,2.728513,2.864939,3.13779,3.13779,4.092769,4.229195,4.229195
16,2026-04-03,ctx1i,158,15.777606,0.099858,9860330000,6.240715e+07,578530633,3.661586e+06,578530633,...,2.531646,2.531646,2.531646,2.531646,2.531646,3.164557,3.164557,3.164557,3.164557,3.164557
17,2026-04-03,v11-payer,342,30.278158,0.088533,27655670000,8.086453e+07,2178586360,6.370136e+06,2178586360,...,4.678363,4.678363,4.093567,4.385965,4.385965,6.140351,4.385965,4.385965,5.263158,5.263158
18,2026-04-04,bhv1n,661,30.098916,0.045535,46810330000,7.081744e+07,2223883833,3.364423e+06,2223883833,...,1.664145,1.664145,1.210287,1.361573,1.664145,2.118003,2.571861,2.874433,3.025719,3.025719
19,2026-04-04,ctx1i,123,11.316394,0.092003,8455540000,6.874423e+07,555837555,4.519005e+06,555837555,...,3.252033,3.252033,4.878049,4.878049,4.878049,4.878049,7.317073,7.317073,8.130081,8.130081
20,2026-04-04,v11-payer,317,25.656932,0.080937,28401120000,8.959344e+07,2430643600,7.667645e+06,2430643600,...,3.470032,3.470032,2.208202,2.839117,4.416404,7.255521,7.255521,7.886435,9.77918,10.094637
21,2026-04-05,bhv1n,931,42.050880,0.045167,64645330000,6.943644e+07,2845404858,3.056289e+06,2845404858,...,1.503759,1.611171,1.718582,2.040816,2.148228,2.255639,1.611171,1.718582,1.718582,1.933405
22,2026-04-05,ctx1i,97,9.389706,0.096801,6018110000,6.204237e+07,355852971,3.668587e+06,351286534,...,5.154639,5.154639,5.154639,5.154639,5.154639,5.154639,5.154639,7.216495,8.247423,8.247423
23,2026-04-05,v11-payer,335,26.147329,0.078052,30894780000,9.222322e+07,2330451593,6.956572e+06,2330451593,...,3.58209,3.58209,5.970149,9.253731,12.537313,13.134328,14.328358,14.328358,14.328358,14.328358
24,2026-04-06,bhv1n,736,33.977247,0.046165,59259880000,8.051614e+07,2762121505,3.752882e+06,2762121505,...,2.173913,2.173913,2.309783,2.445652,2.717391,2.717391,2.717391,2.98913,2.98913,2.98913
25,2026-04-06,ctx1i,158,17.035507,0.107820,13103100000,8.293101e+07,890884258,5.638508e+06,890884258,...,3.797468,3.797468,3.164557,3.164557,3.797468,3.797468,3.797468,3.797468,5.696203,6.329114
26,2026-04-06,v11-payer,241,19.235694,0.079816,25964210000,1.077353e+08,2048832822,8.501381e+06,2048832822,...,3.319502,3.73444,2.904564,3.73444,4.564315,4.564315,5.394191,5.809129,5.809129,6.639004
27,2026-04-07,bhv1n,560,25.974312,0.046383,43485320000,7.765236e+07,2005670300,3.581554e+06,2005670300,...,1.785714,1.785714,2.142857,2.678571,2.857143,2.857143,2.142857,2.321429,2.321429,2.321429
28,2026-04-07,ctx1i,168,17.326205,0.103132,15356990000,9.141065e+07,900632856,5.360910e+06,900632856,...,3.571429,3.571429,4.166667,4.166667,4.761905,4.761905,4.761905,4.761905,4.761905,4.761905
29,2026-04-07,v11-payer,280,20.985509,0.074948,29898580000,1.067806e+08,2095570095,7.484179e+06,2095570095,...,4.642857,4.642857,7.857143,8.214286,8.214286,8.214286,6.785714,6.785714,6.785714,6.785714
30,2026-04-08,bhv1n,690,30.112956,0.043642,49323100000,7.148275e+07,2152101815,3.118988e+06,2144238037,...,0.0,0.0,2.608696,3.043478,3.188406,3.333333,<NA>,<NA>,<NA>,<NA>
31,2026-04-08,ctx1i,181,12.405095,0.068536,20700660000,1.143683e+08,1033033024,5.707365e+06,1033033024,...,0.0,0.0,3.867403,4.41989,4.41989,4.41989,<NA>,<NA>,<NA>,<NA>
32,2026-04-08,v11-payer,221,14.386322,0.065096,21394200000,9.680633e+07,1448547027,6.554511e+06,1448547027,...,0.0,0.0,6.78733,6.78733,6.78733,6.78733,<NA>,<NA>,<NA>,<NA>
33,2026-04-09,bhv1n,1085,42.050948,0.038757,65169770000,6.006430e+07,2688388852,2.477778e+06,2688388852,...,0.0,0.0,1.382488,1.56682,1.56682,1.658986,<NA>,<NA>,<NA>,<NA>
34,2026-04-09,ctx1i,217,19.113353,0.088080,17465320000,8.048535e+07,1006439350,4.637969e+06,1006439350,...,0.0,0.0,3.225806,3.686636,3.686636,3.686636,<NA>,<NA>,<NA>,<NA>
35,2026-04-09,v11-payer,407,16.588085,0.040757,29118910000,7.154523e+07,1469841152,3.611403e+06,1469841152,...,0.0,0.0,5.896806,5.896806,5.896806,5.896806,<NA>,<NA>,<NA>,<NA>
36,2026-04-10,bhv1n,1006,39.474598,0.039239,56129000000,5.579423e+07,2224823966,2.211555e+06,2224823966,...,0.0,0.0,1.491054,2.7833,2.882704,2.882704,<NA>,<NA>,<NA>,<NA>
37,2026-04-10,ctx1i,216,19.484696,0.090207,15154000000,7.015741e+07,823627756,3.813091e+06,823627756,...,0.0,0.0,1.388889,1.851852,1.851852,1.851852,<NA>,<NA>,<NA>,<NA>
38,2026-04-10,v11-payer,377,17.263524,0.045792,27897720000,7.399926e+07,1530796433,4.060468e+06,1530796433,...,0.0,0.0,6.100796,6.100796,6.366048,6.6313,<NA>,<NA>,<NA>,<NA>
39,2026-04-11,bhv1n,900,33.919045,0.037688,49640000000,5.515556e+07,1854449577,2.060500e+06,1854449577,...,0.0,0.0,1.444444,1.888889,1.888889,1.888889,<NA>,<NA>,<NA>,<NA>
40,2026-04-11,ctx1i,256,23.089952,0.090195,18215000000,7.115234e+07,959562540,3.748291e+06,959562540,...,0.0,0.0,2.34375,2.34375,2.34375,2.34375,<NA>,<NA>,<NA>,<NA>
41,2026-04-11,v11-payer,415,13.463586,0.032442,25030840000,6.031528e+07,1191257420,2.870500e+06,1191257420,...,0.0,0.0,4.096386,4.578313,3.614458,3.614458,<NA>,<NA>,<NA>,<NA>
42,2026-04-12,bhv1n,1,0.023006,0.023006,35000000,3.500000e+07,805214,8.052140e+05,805214,...,0.0,0.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
43,2026-04-12,v11-payer,1,0.038907,0.038907,35000000,3.500000e+07,1361730,1.361730e+06,1361730,...,0.0,0.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>

# Outcome: Absolute Purchase event per day per model

In [ ]:
for i in range(0, 8):
    fig = px.line(
        payer_df_all,
        x='submit_date',
        y=f'sum_capped_count_d{i}',
        color='app_event_model_version',
        title=f'Absolute sum_capped_count_d{i} VS Submit Date',
        labels={
            'sum_capped_count_d' + str(i): f'sum_capped_count_d{i}',
            'submit_date': 'Submit Date',
            'app_event_model_version': 'App Event Model Version'
        },
        text=payer_df_all[f'sum_capped_count_d{i}'].round(2) # Add absolute numbers as text, rounded to 2 decimal places
    )
    fig.update_traces(textposition='top center') # Position the text at the top center of each point
    fig.show()

# Model bias

In [ ]:
def model_bias_plot(payer_df_all):
  for i in range(0, 8):
    payer_df_all[f'model_bias_d{i}'] = ( payer_df_all['sum_pred'] / payer_df_all[f'sum_payer_label_d{i}'] - 1) * 100

    # Calculate overall purchase rate for each model for the current day i
    valid_data_df = payer_df_all[
        (payer_df_all[f'sum_payer_label_d{i}'].notna()) &
        (payer_df_all[f'sum_payer_label_d{i}'] != 0)
    ]
    overall_model_bias = valid_data_df.groupby('app_event_model_version').agg(
        total_sum_payer_label = (f'sum_payer_label_d{i}', 'sum'),
        total_pred = ('sum_pred', 'sum')
    ).reset_index()
    overall_model_bias[f'overall_model_bias_d{i}'] = (overall_model_bias[f'total_pred'] / overall_model_bias['total_sum_payer_label'] - 1) * 100

    # Create a subtitle string for the overall rates
    subtitle_parts = []
    for index, row in overall_model_bias.iterrows():
        subtitle_parts.append(f'{row["app_event_model_version"]}: {row[f"overall_model_bias_d{i}"]:.2f}%')
    subtitle_text = 'Average Model Bias: ' + '  |  '.join(subtitle_parts)

    fig = px.line(
        payer_df_all,
        x='submit_date',
        y=f'model_bias_d{i}',
        color='app_event_model_version',
        title=f'Model Prediction Bias D{i} ((sum_pred / sum_payer_label_d{i} ）- 1) * 100 VS Submit Date',
        text=payer_df_all[f'model_bias_d{i}'].round(2) # Add bias numbers as text, rounded to 2 decimal places
    )

    # Add the subtitle as an annotation
    fig.update_layout(
        annotations=[
            dict(
                text=subtitle_text,
                xref='paper',
                yref='paper',
                x=0.5,
                y=0.96, # Adjust y to position it below the main title. This usually works well.
                showarrow=False,
                font=dict(size=15), # Smaller font size
                xanchor='center',
                yanchor='top' # Anchor the top of the text to the y position
            )
        ]
    )

    fig.add_hline(y=0)
    fig.update_traces(textposition='top center') # Position the text at the top center of each point
    fig.show()

model_bias_plot(payer_df_all)

In [ ]:
payer_df_all[["app_event_model_version", "sum_payer_label_d7", "sum_pred"]]

   app_event_model_version  sum_payer_label_d7   sum_pred
0                    bhv1n                  25  40.027658
1                    ctx1i                  38  59.795531
2                v11-payer                  52  89.721261
3                    bhv1n                  17  44.974848
4                    ctx1i                  20  48.297409
5                v11-payer                  43  68.710391
6                    bhv1n                  21  38.430931
7                    ctx1i                  17  47.149240
8                v11-payer                  32  58.506729
9                    bhv1n                  15  32.100694
10                   ctx1i                  11  29.855262
11               v11-payer                  17  39.105158
12                   bhv1n                  13  29.556697
13                   ctx1i                   7  13.884947
14               v11-payer                  12  34.669330
15                   bhv1n                  19  37.746488
16                   ctx1i                   4  15.777606
17               v11-payer                  16  30.278158
18                   bhv1n                  11  30.098916
19                   ctx1i                   4  11.316394
20               v11-payer                  11  25.656932
21                   bhv1n                  15  42.050880
22                   ctx1i                   5   9.389706
23               v11-payer                  12  26.147329
24                   bhv1n                  16  33.977247
25                   ctx1i                   6  17.035507
26               v11-payer                   9  19.235694
27                   bhv1n                  10  25.974312
28                   ctx1i                   6  17.326205
29               v11-payer                  13  20.985509
30                   bhv1n                   0  30.112956
31                   ctx1i                   0  12.405095
32               v11-payer                   0  14.386322
33                   bhv1n                   0  42.050948
34                   ctx1i                   0  19.113353
35               v11-payer                   0  16.588085
36                   bhv1n                   0  39.474598
37                   ctx1i                   0  19.484696
38               v11-payer                   0  17.263524
39                   bhv1n                   0  33.919045
40                   ctx1i                   0  23.089952
41               v11-payer                   0  13.463586
42                   bhv1n                   0   0.023006
43               v11-payer                   0   0.038907

# Product Bias

In [ ]:
def product_bias_plot_per_day_v2(dataframe: pd.DataFrame):
    df = dataframe.copy()

    for day in range(0, 8):
        count_col = f'sum_capped_count_d{day}'
        bias_col = f'product_bias_d{day}'

        # Daily row-wise calculation: (Daily Cost / Daily Count) / Daily Avg Target CPE - 1
        df[bias_col] = (df['sum_cost'] / df[count_col]) / df['avg_tcpe'] - 1

        # Filter for display
        plot_df = df[df[bias_col].notna() & ~df[bias_col].isin([float('inf'), float('-inf')])]

        # Calculate overall aggregated bias across all dates for the subtitle
        valid_data_df = df[(df[count_col].notna()) & (df[count_col] != 0)]

        if not valid_data_df.empty:
            overall_stats = valid_data_df.groupby('app_event_model_version').agg(
                total_cost=('sum_cost', 'sum'),
                total_count=(count_col, 'sum'),
                mean_tcpe=('avg_tcpe', 'mean')
            ).reset_index()
            overall_stats['overall_bias'] = (overall_stats['total_cost'] / overall_stats['total_count']) / overall_stats['mean_tcpe'] - 1

            subtitle_parts = [f"{row['app_event_model_version']}: {row['overall_bias']:.2f}" for _, row in overall_stats.iterrows()]
            subtitle_text = 'Overall Aggregated Bias: ' + '  |  '.join(subtitle_parts)
        else:
            subtitle_text = "No valid data for overall bias"

        fig = px.line(
            plot_df,
            x='submit_date',
            y=bias_col,
            color='app_event_model_version',
            title=f'Product Bias D{day} Over Time: ((Observed CPE / Target CPE) - 1)',
            labels={'submit_date': 'Submit Date', bias_col: 'Bias'},
            text=plot_df[bias_col].round(2) if not plot_df.empty else None
        )

        fig.update_layout(
            annotations=[
                dict(
                    text=subtitle_text,
                    xref='paper', yref='paper',
                    x=0.5, y=0.96,
                    showarrow=False,
                    font=dict(size=13),
                    xanchor='center', yanchor='top'
                )
            ]
        )

        fig.add_hline(y=0, line_dash="dash", line_color="black")
        fig.update_traces(textposition='top center')

        # Ensure x-axis shows the relevant date range even if data is missing
        fig.update_xaxes(range=[df['submit_date'].min(), df['submit_date'].max()])

        fig.show()

product_bias_plot_per_day_v2(payer_df_all)

In [ ]:
payer_df_all.keys()

Index(['submit_date', 'app_event_model_version', 'installs', 'sum_pred',
       'avg_pred', 'sum_tcpe', 'avg_tcpe', 'sum_cost', 'avg_cost',
       'sum_campaign_spend', 'sum_payer_label_d0', 'sum_payer_label_d1',
       'sum_payer_label_d2', 'sum_payer_label_d3', 'sum_payer_label_d4',
       'sum_payer_label_d5', 'sum_payer_label_d6', 'sum_payer_label_d7',
       'sum_capped_count_d0', 'sum_capped_count_d1', 'sum_capped_count_d2',
       'sum_capped_count_d3', 'sum_capped_count_d4', 'sum_capped_count_d5',
       'sum_capped_count_d6', 'sum_capped_count_d7', 'sum_capped_deposit_d0',
       'sum_capped_deposit_d1', 'sum_capped_deposit_d2',
       'sum_capped_deposit_d3', 'sum_capped_deposit_d4',
       'sum_capped_deposit_d5', 'sum_capped_deposit_d6',
       'sum_capped_deposit_d7', 'payer_date_d0', 'payer_date_d1',
       'payer_date_d2', 'payer_date_d3', 'payer_date_d4', 'payer_date_d5',
       'payer_date_d6', 'payer_date_d7', 'purchase_date_d0',
       'purchase_date_d1', 'purchase_date_d2', 'purchase_date_d3',
       'purchase_date_d4', 'purchase_date_d5', 'purchase_date_d6',
       'purchase_date_d7', 'model_bias_d0', 'model_bias_d1', 'model_bias_d2',
       'model_bias_d3', 'model_bias_d4', 'model_bias_d5', 'model_bias_d6',
       'model_bias_d7'],
      dtype='object')

### Product Bias Analysis per Day (Time-Series with Overall Aggregation)

In [ ]:
def product_bias_plot_per_day_v2(dataframe: pd.DataFrame):
    df = dataframe.copy()

    for day in range(0, 8):
        count_col = f'sum_capped_count_d{day}'
        bias_col = f'product_bias_d{day}'

        # Daily row-wise calculation: (Daily Cost / Daily Count) / Daily Avg Target CPE - 1
        df[bias_col] = (df['sum_cost'] / df[count_col]) / df['avg_tcpe'] - 1

        # Filter for display
        plot_df = df[df[bias_col].notna() & ~df[bias_col].isin([float('inf'), float('-inf')])]

        # Calculate overall aggregated bias across all dates for the subtitle
        valid_data_df = df[(df[count_col].notna()) & (df[count_col] != 0)]

        if not valid_data_df.empty:
            overall_stats = valid_data_df.groupby('app_event_model_version').agg(
                total_cost=('sum_cost', 'sum'),
                total_count=(count_col, 'sum'),
                mean_tcpe=('avg_tcpe', 'mean')
            ).reset_index()
            overall_stats['overall_bias'] = (overall_stats['total_cost'] / overall_stats['total_count']) / overall_stats['mean_tcpe'] - 1

            subtitle_parts = [f"{row['app_event_model_version']}: {row['overall_bias']:.2f}" for _, row in overall_stats.iterrows()]
            subtitle_text = 'Overall Aggregated Bias: ' + '  |  '.join(subtitle_parts)
        else:
            subtitle_text = "No valid data for overall bias"

        fig = px.line(
            plot_df,
            x='submit_date',
            y=bias_col,
            color='app_event_model_version',
            title=f'Product Bias D{day} Over Time: ((Observed CPE / Target CPE) - 1)',
            labels={'submit_date': 'Submit Date', bias_col: 'Bias'},
            text=plot_df[bias_col].round(2) if not plot_df.empty else None
        )

        fig.update_layout(
            annotations=[
                dict(
                    text=subtitle_text,
                    xref='paper', yref='paper',
                    x=0.5, y=0.96,
                    showarrow=False,
                    font=dict(size=13),
                    xanchor='center', yanchor='top'
                )
            ]
        )

        fig.add_hline(y=0, line_dash="dash", line_color="black")
        fig.update_traces(textposition='top center')

        # Ensure x-axis shows the relevant date range even if data is missing
        fig.update_xaxes(range=[df['submit_date'].min(), df['submit_date'].max()])

        fig.show()

product_bias_plot_per_day_v2(payer_df_all)